### ISSUE TITLE
Implement "osm-health version"

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm-health#115]
```console
$ ./bin/osm-health version
3:55PM INF osm-health version: dev; 12f43f6b7ac8d446e7f29961f59d064a7edca3af; 2021-11-16 file=main.go:65 module=main
Error: unknown command "version" for "osm-health"
Run 'osm-health --help' for usage.
```

It would be useful to run `osm-health version1` and see the version currently installed

**Comment by johnsonshi** [comment]
The `osm` cli already has this functionality under `osm version`, which shows the local CLI version and the remote mesh version. I don't think it is a good decision to duplicate this work within `osm`, especially since `osm-health` and its functionality may be merged into the main `osm` cli in the future.

I propose that we recommend users to use `osm version` when checking versions and close this issue.

cc @draychev and @jaellio

**Comment by johnsonshi** [comment]
`osm version` command in the main cli already implements this.
